Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/windows-11-21h2-enterprise"
  config.vm.box_version = "2102.0.2404"
  config.vm.provider "vmware_desktop"

  config.vm.synced_folder "./shared", "/vagrant_data"

  config.vm.provision "shell", path: "setup.ps1", env: {
    "ELK_ENDPOINT" => "127.0.0.1:9200"
  }
end